# Tomcat instance particulars

servers:
  - host: "localhost"
    port: 9044
    username: "monitorRole"
    password: "tomcat"
    displayName: "localhost"

# Tomcat MBeans
mbeans:
  - domainName: "Catalina"
    types: [ThreadPool,GlobalRequestProcessor]
    excludePatterns: [connectionCount]
        

# number of concurrent tasks
numberOfThreads: 10

#timeout for the thread
threadTimeout: 30

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|Tomcat|"

