# Tomcat instance particulars

server:
    host: "localhost"
    port: 9044
    username: "monitorRole"
    password: "tomcat"

# Tomcat MBeans
mbeans:
    domainName: "Catalina"
    types: [ThreadPool,GlobalRequestProcessor]

    excludePatterns: [connectionCount]
        

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|Tomcat|"

